# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0a7d0553fea6fba64a4d7b779d1eaeab4859ece5e4b1244c1979f37cc63843d1cd54cc6490fda5efbe9d0bddb0ad53b44d5679c0942d1d4abab68d54da0ae9b5

test:
  secret_key_base: 10eab0a56f419e1b8309f6c44cffde8a87d46e0c8aaa2e95444c6db9e87b4cca2506b18a0abbdee6efe75e26bfd0e833ac8df7a27c74a6930e67f8324c26ffc0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
